### ISSUE TITLE
Error with parsing dates

### ISSUE THREAD

**Issue by QasimKhan5x** [YuriyIvon/DatabaseBenchmark#2]
I am using the 0.9.10 release for Windows x64. I followed exactly your instructions in the [Medium article]() with the sales data but I am getting this error even after removing the spaces from the column names:

```
DatabaseBenchmark import --DatabaseType=Postgres --ConnectionString="Host=localhost;Port=5432;Database=benchmark;Username=postgres;Password=password" --TableFilePath=SalesTable.json --DataSourceType=Csv --DataSourceFilePath="1000000 Sales Records.csv"

CsvHelper.TypeConversion.TypeConverterException: The conversion cannot be performed.
    Text: '7/27/2012'
    MemberName:
    MemberType:
    TypeConverter: 'CsvHelper.TypeConversion.NullableConverter'
IReader state:
   ColumnCount: 0
   CurrentIndex: 5
   HeaderRecord:
["Region","Country","ItemType","SalesChannel","OrderPriority","OrderDate","OrderID","ShipDate","UnitsSold","UnitPrice","UnitCost","TotalRevenue","TotalCost","TotalProfit"]
IParser state:
   ByteCount: 0
   CharCount: 264
   Row: 2
   RawRow: 2
   Count: 14
   RawRecord:
Sub-Saharan Africa,South Africa,Fruits,Offline,M,7/27/2012,443368995,7/28/2012,1593,9.33,6.92,14862.69,11023.56,3839.13


   at CsvHelper.TypeConversion.DefaultTypeConverter.ConvertFromString(String text, IReaderRow row, MemberMapData memberMapData)
   at CsvHelper.TypeConversion.DateTimeConverter.ConvertFromString(String text, IReaderRow row, MemberMapData memberMapData)
   at CsvHelper.TypeConversion.NullableConverter.ConvertFromString(String text, IReaderRow row, MemberMapData memberMapData)
   at CsvHelper.CsvReader.GetField(Type type, Int32 index, ITypeConverter converter)
   at CsvHelper.CsvReader.GetField(Type type, String name, ITypeConverter converter)
   at CsvHelper.CsvReader.GetField(Type type, String name)
   at DatabaseBenchmark.DataSources.Csv.CsvDataSource.GetValue(Type type, String name) in /home/runner/work/DatabaseBenchmark/DatabaseBenchmark/src/DatabaseBenchmark/DataSources/Csv/CsvDataSource.cs:line 33
   at DatabaseBenchmark.Databases.PostgreSql.PostgreSqlDataImporter.Import() in /home/runner/work/DatabaseBenchmark/DatabaseBenchmark/src/DatabaseBenchmark/Databases/PostgreSql/PostgreSqlDataImporter.cs:line 51
   at DatabaseBenchmark.Commands.ImportCommand.Execute() in /home/runner/work/DatabaseBenchmark/DatabaseBenchmark/src/DatabaseBenchmark/Commands/ImportCommand.cs:line 44
   at Program.<Main>$(String[] args) in /home/runner/work/DatabaseBenchmark/DatabaseBenchmark/src/DatabaseBenchmark/Program.cs:line 10
```

**Comment by QasimKhan5x** [comment]
Found out that the issue was that the date in the files is formatted as "M/DD/YYYY" but it should have been "DD/MM/YYYY"

**Comment by YuriyIvon** [comment]
There is a command-line parameter `--DataSource.Csv.Culture` that specifies the source file culture, which also controls the date format.
